---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7
    driver:
      box: bento/centos-7
      box_url: https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1811_02.VirtualBox.box
    driver_config:
      network:
      - ["forwarded_port", { guest: 8080, host: 8080 }]
      - ["private_network", { ip: "192.168.33.1"} ]

suites:
  - name: default
    run_list:
      - recipe[acme-jenkins::master]
      - recipe[acme-jenkins::plugins]
